-- ==========================================
-- 1. CREACIÓN DE TABLAS
-- ==========================================

-- Tabla de Tickets
CREATE TABLE public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'Open',
    priority TEXT NOT NULL DEFAULT 'Medium',
    ticket_type TEXT DEFAULT 'Task',
    created_by TEXT, -- Almacena el Session.User.Id (UUID en formato texto)
    assigned_to TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    due_date TIMESTAMP WITH TIME ZONE
);

-- Tabla de Comentarios
CREATE TABLE public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    commment_text TEXT, -- Escrito exactamente como tu atributo C#: [Column("commment_text")]
    created_by TEXT, -- Almacena el Session.User.Id
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 2. POLÍTICAS DE SEGURIDAD (RLS)
-- ==========================================

-- Habilitar RLS en ambas tablas
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Políticas para Tickets (Solo autenticados)
CREATE POLICY "Lectura tickets" ON public.tickets FOR SELECT TO authenticated USING (true);
CREATE POLICY "Insertar tickets" ON public.tickets FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Actualizar tickets" ON public.tickets FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Políticas para Comentarios (El controlador permite Leer, Insertar y Borrar)
CREATE POLICY "Lectura comentarios" ON public.comments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Insertar comentarios" ON public.comments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Borrar comentarios" ON public.comments FOR DELETE TO authenticated USING (true);

-- ==========================================
-- 3. DATOS DE PRUEBA (DUMMY DATA)
-- ==========================================

-- Insertar tickets de prueba
INSERT INTO public.tickets (title, description, status, priority, ticket_type, created_by, assigned_to, due_date)
VALUES 
    ('Pantalla azul al iniciar', 'El equipo de recepción muestra BSOD al arrancar Windows.', 'Open', 'High', 'Issue', 'user-system', 'Soporte Nivel 1', '2026-07-10 10:00:00+00'),
    ('Licencia de Office vencida', 'Necesito que renueven mi licencia de Office 365.', 'In Progress', 'Medium', 'Request', 'user-system', 'Soporte Nivel 2', '2026-07-08 15:30:00+00'),
    ('Mantenimiento de servidor', 'Actualización programada del parche de seguridad mensual.', 'Closed', 'Low', 'Task', 'user-system', 'Infraestructura', '2026-07-01 02:00:00+00');

-- Insertar comentarios de prueba (vinculados a los tickets anteriores)
INSERT INTO public.comments (ticket_id, commment_text, created_by)
VALUES 
    (1, 'Revisé el equipo, parece ser un problema de memoria RAM. Pediré repuestos.', 'Técnico Juan'),
    (2, 'La solicitud ya fue escalada al departamento de compras.', 'Técnico Ana');



//Mas Dummy Data tomando en cuenta 3 usuarios creados para realizar pruebas en el DB
-- ==========================================
-- 1. INSERCIÓN DE TICKETS (15 Entradas)
-- ==========================================
INSERT INTO public.tickets (id, title, description, status, priority, ticket_type, created_by, assigned_to, due_date)
VALUES 
    -- --------------------------------------------------------
    -- USUARIO 1: 4c9905f7-b0ce-4780-a227-a25e2fa9d4d0
    -- --------------------------------------------------------
    (1001, 'Acceso a repositorio GitHub', 'Solicito permisos de lectura para el repositorio del proyecto final.', 'Open', 'Medium', 'Request', '4c9905f7-b0ce-4780-a227-a25e2fa9d4d0', 'IT Admin', '2026-07-15 00:00:00+00'),
    (1002, 'Error de timeout en BD', 'La aplicación MVC está dando timeout intermitente al conectar con Supabase en producción.', 'In Progress', 'High', 'Issue', '4c9905f7-b0ce-4780-a227-a25e2fa9d4d0', 'DBA Team', '2026-07-06 12:00:00+00'),
    (1003, 'Renovación de licencia IDE', 'Necesito renovar la licencia corporativa para el entorno de desarrollo.', 'Closed', 'Low', 'Request', '4c9905f7-b0ce-4780-a227-a25e2fa9d4d0', 'Soporte TI', NULL),
    (1004, 'Reemplazo de batería de laptop', 'La batería de mi equipo se descarga en menos de 15 minutos sin estar conectada.', 'Open', 'Medium', 'Issue', '4c9905f7-b0ce-4780-a227-a25e2fa9d4d0', 'Hardware', '2026-07-10 00:00:00+00'),
    (1005, 'Actualizar documentación de API', 'Falta documentar los nuevos endpoints de autenticación en Swagger.', 'Blocked', 'Low', 'Task', '4c9905f7-b0ce-4780-a227-a25e2fa9d4d0', 'DevOps', NULL),

    -- --------------------------------------------------------
    -- USUARIO 2: 50976f02-dabc-456b-8d6e-5446aad84b6c
    -- --------------------------------------------------------
    (1006, 'No puedo acceder a la VPN', 'El cliente VPN se queda cargando al 40% y da error de credenciales.', 'Open', 'High', 'Issue', '50976f02-dabc-456b-8d6e-5446aad84b6c', 'Redes', '2026-07-05 08:00:00+00'),
    (1007, 'Crear ambiente de pruebas', 'Se requiere aprovisionar un entorno de staging para QA.', 'In Progress', 'Medium', 'Task', '50976f02-dabc-456b-8d6e-5446aad84b6c', 'Infraestructura', '2026-07-20 00:00:00+00'),
    (1008, 'Error 500 en página de Login', 'Los usuarios reportan una pantalla blanca al ingresar la clave incorrecta.', 'Open', 'High', 'Issue', '50976f02-dabc-456b-8d6e-5446aad84b6c', 'Desarrollo', NULL),
    (1009, 'Aumento de memoria RAM', 'Mi máquina virtual se queda sin memoria al compilar el proyecto.', 'Closed', 'Medium', 'Request', '50976f02-dabc-456b-8d6e-5446aad84b6c', 'Hardware', NULL),
    (1010, 'Configuración de reglas de Firewall', 'Ocupo que abran el puerto 5432 para acceder a la base de datos remotamente.', 'Blocked', 'High', 'Task', '50976f02-dabc-456b-8d6e-5446aad84b6c', 'Seguridad', '2026-07-08 00:00:00+00'),

    -- --------------------------------------------------------
    -- USUARIO 3: d06766c0-fe2d-44c8-ba5c-296b2ce04e6d
    -- --------------------------------------------------------
    (1011, 'Proyector dañado en sala B', 'El proyector no enciende, parpadea una luz roja indicando error de lámpara.', 'Open', 'Medium', 'Issue', 'd06766c0-fe2d-44c8-ba5c-296b2ce04e6d', 'Soporte TI', '2026-07-07 14:00:00+00'),
    (1012, 'Usuario de base de datos', 'Crear usuario de solo lectura (read-only) para el equipo de auditoría.', 'In Progress', 'Low', 'Task', 'd06766c0-fe2d-44c8-ba5c-296b2ce04e6d', 'DBA Team', '2026-07-12 00:00:00+00'),
    (1013, 'Restaurar carpeta borrada', 'Borré accidentalmente la carpeta de reportes financieros de SharePoint.', 'Closed', 'High', 'Issue', 'd06766c0-fe2d-44c8-ba5c-296b2ce04e6d', 'SysAdmin', NULL),
    (1014, 'Bug visual en móvil', 'La tabla de tickets se desborda y no se ve bien en pantallas de teléfonos.', 'Open', 'Medium', 'Issue', 'd06766c0-fe2d-44c8-ba5c-296b2ce04e6d', 'Frontend Dev', NULL),
    (1015, 'Desplegar parche a producción', 'Urge subir el hotfix del módulo de autenticación para los usuarios.', 'In Progress', 'High', 'Task', 'd06766c0-fe2d-44c8-ba5c-296b2ce04e6d', 'DevOps', '2026-07-05 23:59:00+00');


-- ==========================================
-- 2. INSERCIÓN DE COMENTARIOS
-- ==========================================
INSERT INTO public.comments (ticket_id, commment_text, created_by)
VALUES 
    (1002, 'Estamos analizando los logs del servidor para encontrar el cuello de botella.', '50976f02-dabc-456b-8d6e-5446aad84b6c'),
    (1002, 'Parece ser un problema con la cantidad máxima de conexiones del pool.', 'd06766c0-fe2d-44c8-ba5c-296b2ce04e6d'),
    (1004, 'La batería nueva ya fue solicitada a bodega. Llega en 2 días.', '50976f02-dabc-456b-8d6e-5446aad84b6c'),
    (1006, 'Asegúrate de tener la última versión del cliente instalada.', '4c9905f7-b0ce-4780-a227-a25e2fa9d4d0'),
    (1006, 'Ya actualicé, pero sigue fallando. Adjunto captura de pantalla.', '50976f02-dabc-456b-8d6e-5446aad84b6c'),
    (1010, 'La solicitud está en pausa hasta recibir aprobación de la gerencia.', 'd06766c0-fe2d-44c8-ba5c-296b2ce04e6d'),
    (1013, 'Carpeta restaurada exitosamente desde el backup de ayer a las 2 AM.', '4c9905f7-b0ce-4780-a227-a25e2fa9d4d0');


-- ==========================================
-- 3. SINCRONIZACIÓN DEL CONTADOR DE IDs (IDENTITY SEQUENCE)
-- ==========================================
-- Esto asegura que el próximo ticket que crees desde tu app no dé error de Primary Key duplicada
SELECT setval(pg_get_serial_sequence('public.tickets', 'id'), (SELECT MAX(id) FROM public.tickets));
SELECT setval(pg_get_serial_sequence('public.comments', 'id'), (SELECT MAX(id) FROM public.comments));